export const projectData = [
  {
    id: 1,
    name: 'CoronaLiveTracker',
    category: 'Vanilla JS',
    show: false,
    link: 'https://coronalivetracker.netlify.app/',
    path: 'javascript',
  },
  {
    id: 2,
    name: 'Hoikurumunozomi',
    category: 'React JS',
    show: false,
    link: 'https://hoikurumunozomi-test.netlify.app/',
    path: 'react',
  },
  {
    id: 3,
    name: 'First Portfolio',
    category: 'HTML/CSS',
    show: false,
    link: undefined,
    path: 'htmlcss',
  },
  {
    id: 4,
    name: 'Course Schedule',
    category: 'Vanilla JS',
    show: false,
    link: undefined,
    path: 'javascript',
  },
  {
    id: 5,
    name: 'Women In A Cage',
    category: 'React JS',
    show: false,
    link: 'https://ih-presentation.netlify.app/',
    path: 'react',
  },
  {
    id: 6,
    name: 'Philosophy Project',
    category: 'React JS',
    show: false,
    link: 'https://ih2-site.netlify.app/',
    fullScreen: '',
    path: 'react',
  },
  {
    id: 7,
    name: 'Portfolio Main',
    category: 'React JS',
    show: false,
    link: undefined,
    path: 'react',
  },
];
